apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-portal
  namespace: ev91
  labels:
    app: admin-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-portal
  template:
    metadata:
      labels:
        app: admin-portal
    spec:
      containers:
      - name: admin-portal
        image: sanjub07/admin-portal:latest   # Make sure image is rebuilt with VITE_API_BASE_URL pointing to public API URL
        ports:
        - containerPort: 3003
        env:
        - name: VITE_NODE_ENV
          value: "production"
        # Optional: You can remove VITE_API_BASE_URL here if baked into image at build time
        - name: VITE_API_BASE_URL
          value: "http://http://a94cf28e9c64d425d9e966da372c9eec-1478021238.ap-south-1.elb.amazonaws.com//api"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: admin-portal
  namespace: ev91
spec:
  selector:
    app: admin-portal
  ports:
    - port: 80
      targetPort: 3003
  type: ClusterIP
