apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider-service
  namespace: ev91
  labels:
    app: rider-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rider-service
  template:
    metadata:
      labels:
        app: rider-service
    spec:
      containers:
      - name: rider-service
        image: sanjub07/rider-service:latest
        ports:
        - containerPort: 4005
        env:
        - name: PORT
          value: "4005"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ev91-db-secrets
              key: rider-service-db-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ev91-jwt-secrets
              key: jwt-secret
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ev91-aws-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ev91-aws-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          value: "ap-south-1"
        - name: AWS_S3_BUCKET
          value: "ev91-rider-docs"
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: ev91-twilio-secrets
              key: twilio-account-sid
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: ev91-twilio-secrets
              key: twilio-auth-token
        envFrom:
        - configMapRef:
            name: ev91-service-config
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
          requests:
            memory: "1Gi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /api/v1/health/live
            port: 4005
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/v1/health/ready
            port: 4005
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 3


---
apiVersion: v1
kind: Service
metadata:
  name: rider-service
  namespace: ev91
spec:
  selector:
    app: rider-service
  ports:
    - port: 4005
      targetPort: 4005
  type: ClusterIP  

