apiVersion: apps/v1
kind: Deployment
metadata:
  name: spare-parts-service
  namespace: ev91
  labels:
    app: spare-parts-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spare-parts-service
  template:
    metadata:
      labels:
        app: spare-parts-service
    spec:
      containers:
      - name: spare-parts-service
        image: sanjub07/spare-parts-service:latest
        ports:
        - containerPort: 4010
        env:
        - name: PORT
          value: "4010"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ev91-db-secrets
              key: spare-parts-service-db-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ev91-jwt-secrets
              key: jwt-secret
        envFrom:
        - configMapRef:
            name: ev91-service-config
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4010
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 4010
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: spare-parts-service
  namespace: ev91
spec:
  selector:
    app: spare-parts-service
  ports:
    - port: 4010
      targetPort: 4010
  type: ClusterIP  
